"use client";
import { useState } from "react";
import { formatCoachTimestamp, formatCoachTimestampList, formatCoachTimestampText } from "../../lib/replayCoachTime";
import type { CoachAnalysis, CoachDisplay, ExecutedTradeVerdict, FullSessionPlan } from "../../types/replay";
import ReplayCoachConversation from "./ReplayCoachConversation";

const money = (n: number | null) => n === null ? "Not applicable" : `₹${n.toFixed(2)}`;
const prose = (value: string) => formatCoachTimestampText(value);
function DecisionQuality({ display }: { display: CoachDisplay }) { const s = display.decision_quality_score; return <article className="min-w-0 rounded border border-indigo-500/60 bg-slate-950 p-4"><div className="flex justify-between"><h3 className="font-semibold">Decision Quality Score</h3><b>{s.overall_score}/{s.maximum_score}</b></div><p className="mt-2 text-sm">{prose(s.summary)}</p><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Check</th><th>Score</th><th>Evidence</th><th>What it means</th></tr></thead><tbody>{s.components.map(c => <tr key={c.component} className="border-t border-slate-800 align-top"><th>{c.label}</th><td>{c.score}/{c.maximum_score}</td><td>{prose(`${c.observed_value}; ${c.baseline}`)}</td><td>{prose(c.beginner_explanation)}</td></tr>)}</tbody></table></article>; }
function Executed({ verdict }: { verdict: ExecutedTradeVerdict }) { return <article className="min-w-0 rounded border border-gray-700 bg-gray-950 p-4"><div className="flex gap-2"><b>{verdict.outcome_status}</b><b>{verdict.plan_standard_status === "BELOW_REQUIRED_RR" ? "BELOW 1:4 RULE" : "MEETS 1:4 RULE"}</b></div><h3 className="mt-3 font-semibold">Executed Trade Verdict</h3><table className="mt-3 w-full text-left text-sm"><thead><tr><th>Component</th><th>Value</th><th>Meaning</th></tr></thead><tbody>{verdict.rows.map(r => <tr key={r.component} className="border-t border-gray-800 align-top"><th>{r.component}</th><td>{prose(r.value)}</td><td>{prose(r.meaning)}</td></tr>)}</tbody></table></article>; }
function FullPlan({ plan }: { plan: FullSessionPlan }) { const [evidence, setEvidence] = useState(false); const rows: [string, string, string][] = [["Best opportunity", `${plan.trade_name} · ${plan.opportunity_score}/10`, plan.score_explanation], ["Direction", plan.direction, plan.market_story], ["Decision time", plan.decision_time ? formatCoachTimestamp(plan.decision_time) : "Not established", plan.setup_explanation], ["Entry trigger", plan.entry_trigger, "Completed-candle condition before entry."], ["Entry", plan.entry_price_upper ? `${money(plan.entry_price)} – ${money(plan.entry_price_upper)}` : money(plan.entry_price), "Planned entry location."], ["Structural stop", money(plan.stop_price), plan.invalidation_condition], ["Target", money(plan.target_price), "Session structure target."], ["Risk", money(plan.risk), "Backend calculated per share."], ["Reward", money(plan.reward), "Backend calculated per share."], ["Reward-to-risk", plan.reward_to_risk === null ? "Not applicable" : `${plan.reward_to_risk.toFixed(2)}:1`, `${plan.ratio_status}; required ${plan.required_reward_to_risk}:1.`], ["Volume", plan.volume_explanation, "Participation at the decision time."], ["NIFTY", plan.nifty_explanation, "Market alignment."], ["Beginner lesson", plan.beginner_lesson, "How to recognize this setup next time."]]; const decisionTimes = formatCoachTimestampList(plan.decision_evidence_times); const outcomeTimes = formatCoachTimestampList(plan.outcome_evidence_times); return <article className="rounded border border-indigo-500/60 bg-gray-950 p-4"><h3 className="font-semibold">Best Full-Session Trade Plan</h3><p className="mt-2 text-sm text-indigo-100">{prose(plan.market_story)}</p><p className="mt-2 text-sm text-gray-300">{prose(plan.setup_explanation)}</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[40rem] text-left text-sm"><thead><tr><th>Component</th><th>Plan</th><th>Why</th></tr></thead><tbody>{rows.map(r => <tr key={r[0]} className="border-t border-gray-800 align-top"><th>{r[0]}</th><td>{prose(r[1])}</td><td>{prose(r[2])}</td></tr>)}</tbody></table></div><button className="mt-3 text-sm text-indigo-300" onClick={() => setEvidence(!evidence)}>{evidence ? "Hide" : "View"} supporting chart evidence</button>{evidence && <div className="mt-2 grid gap-3 text-sm md:grid-cols-2"><div><b>Evidence available at decision time</b><p>{decisionTimes.join(", ") || "None supplied"}</p></div><div><b>What happened afterward</b><p>{outcomeTimes.join(", ") || "None supplied"}</p></div></div>}</article>; }
export default function ReplayCoachPanel({ analysis, coachDisplay, analysisId, loading, error, onRetry, onEvidenceTime }: { analysis: CoachAnalysis | null; coachDisplay: CoachDisplay | null; analysisId: number | null; loading: boolean; error: string | null; onRetry: () => void; onEvidenceTime: (time: string) => void }) { const [details, setDetails] = useState(false); return <section className="mb-6 rounded-lg border border-indigo-700 bg-gray-900 p-5"><h2 className="text-xl font-bold">Trade Replay Coach</h2><p className="mt-1 text-xs text-gray-400">All times are IST.</p>{loading && <p>Analyzing…</p>}{error && <div><p>{error}</p><button onClick={onRetry}>Retry Coach analysis</button></div>}{coachDisplay && <div className="mt-4 space-y-5"><div className="grid gap-5 xl:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]"><DecisionQuality display={coachDisplay} /><Executed verdict={coachDisplay.executed_trade_verdict} /></div>{coachDisplay.best_full_session_plan ? <FullPlan plan={coachDisplay.best_full_session_plan} /> : <p className="text-sm text-gray-400">Full-session plan not available for this saved analysis.</p>}{analysisId && <ReplayCoachConversation analysisId={analysisId} onEvidenceTime={onEvidenceTime} />}{analysis && coachDisplay.detailed_evidence_available && <div><button onClick={() => setDetails(!details)}>{details ? "Hide" : "View"} detailed evidence</button>{details && <pre className="overflow-auto">{JSON.stringify(analysis, null, 2)}</pre>}</div>}</div>}</section>; }
