"use client";

import { AlternativeTradePlan, CoachAnalysis, CoachPoint } from "../../types/replay";

function Evidence({ points }: { points: CoachPoint[] }) {
    if (!points.length) return <p className="text-sm text-gray-400">No specific points returned.</p>;
    return <ul className="space-y-3">{points.map((item, index) => <li key={`${item.point}-${index}`} className="rounded bg-gray-800 p-3"><p>{item.point}</p>{item.why_it_matters && <p className="mt-1 text-sm text-amber-200">Why it matters: {item.why_it_matters}</p>}<ul className="mt-2 space-y-1 text-sm text-gray-300">{item.evidence.map((evidence, evidenceIndex) => <li key={`${evidence.time}-${evidenceIndex}`}><span className="text-blue-300">{evidence.time}</span> — Stock: {evidence.stock_values}; Market: {evidence.market_values}{evidence.calculation ? `; Calculation: ${evidence.calculation}` : ""}</li>)}</ul></li>)}</ul>;
}

function Plan({ plan }: { plan: AlternativeTradePlan }) {
    const color = plan.decision === "TAKE" ? "bg-emerald-700" : plan.decision === "WAIT" ? "bg-amber-700" : "bg-slate-600";
    const prices = [["Entry", plan.entry_price], ["Stop", plan.stop_price], ["Target", plan.target_price], ["Risk", plan.risk], ["Reward", plan.reward], ["R/R", plan.risk_reward_ratio]].filter(([, value]) => value !== null);
    return <article className="rounded border border-gray-700 bg-gray-900 p-4"><div className="flex items-center gap-2"><h4 className="font-semibold">{plan.name}</h4><span className={`rounded px-2 py-0.5 text-xs font-bold ${color}`}>{plan.decision}</span>{plan.side && <span className="text-sm text-gray-300">{plan.side}</span>}</div><p className="mt-2 text-sm">{plan.entry_condition}</p>{prices.length > 0 && <p className="mt-2 text-sm text-gray-300">{prices.map(([label, value]) => `${label}: ${value}`).join(" · ")}</p>}<p className="mt-2 text-sm">Rating: {plan.rating}/10</p><p className="mt-2 text-sm text-gray-300">Why: {plan.why_good.join("; ")}</p><p className="mt-1 text-sm text-gray-300">Risks: {plan.risks.join("; ")}</p>{plan.evidence_times.length > 0 && <p className="mt-1 text-sm text-blue-300">Evidence: {plan.evidence_times.join(", ")}</p>}</article>;
}

export default function ReplayCoachPanel({ analysis, loading, error, onRetry }: { analysis: CoachAnalysis | null; loading: boolean; error: string | null; onRetry: () => void }) {
    return <section className="mb-6 rounded-lg border border-indigo-700 bg-gray-900 p-5"><h2 className="text-xl font-bold">Trade Replay Coach</h2>{loading && <p className="mt-3 text-indigo-300">Analyzing the executed trade and full market session…</p>}{error && <div className="mt-3"><p className="text-red-300">{error}</p><button onClick={onRetry} disabled={loading} className="mt-3 rounded bg-indigo-600 px-3 py-2 text-sm disabled:bg-gray-700">Retry Coach analysis</button></div>}{analysis && <div className="mt-4 space-y-6"><div><h3 className="font-semibold">Executed-trade analysis</h3><p className="mt-2">{analysis.executed_trade_analysis.summary}</p><h4 className="mt-4 font-medium text-emerald-300">What was good</h4><Evidence points={analysis.executed_trade_analysis.good} /><h4 className="mt-4 font-medium text-amber-300">What was weak</h4><Evidence points={analysis.executed_trade_analysis.bad} /><h4 className="mt-4 font-medium">How to improve</h4><ul className="mt-2 space-y-2 text-sm text-gray-300">{analysis.executed_trade_analysis.how_to_improve.map((item, index) => <li key={index}><b>{item.action}</b>: {item.rule} — {item.example_using_this_trade}</li>)}</ul></div><div><h3 className="font-semibold">Alternative trade plans</h3><div className="mt-3 grid gap-3 lg:grid-cols-3">{analysis.alternative_trade_plans.map((plan, index) => <Plan key={`${plan.name}-${index}`} plan={plan} />)}</div></div><div><h3 className="font-semibold">Key learning</h3><p className="mt-2">{analysis.key_learning.lesson}</p><p className="text-sm text-gray-300">Rule: {analysis.key_learning.numeric_rule}</p><p className="text-sm text-gray-300">Example: {analysis.key_learning.example_using_this_trade}</p></div><div><h3 className="font-semibold">Limitations</h3><ul className="mt-2 list-disc pl-5 text-sm text-gray-300">{analysis.limitations.map((item, index) => <li key={index}>{item}</li>)}</ul></div></div>}</section>;
}
