# IntradayTradeStockAnalyser/backend/constants/eventTypes.py

from enum import Enum


class EventType(str, Enum):
    BREAKOUT = "BREAKOUT"
    BREAKDOWN = "BREAKDOWN"

    VWAP_RECLAIM = "VWAP_RECLAIM"
    VWAP_REJECTION = "VWAP_REJECTION"

    RELATIVE_STRENGTH = "RELATIVE_STRENGTH"
    RELATIVE_WEAKNESS = "RELATIVE_WEAKNESS"

    ORB_BREAKOUT = "ORB_BREAKOUT"
    ORB_BREAKDOWN = "ORB_BREAKDOWN"

    MOMENTUM_CONTINUATION = "MOMENTUM_CONTINUATION"
    PULLBACK_CONTINUATION = "PULLBACK_CONTINUATION"

    VOLUME_EXPANSION = "VOLUME_EXPANSION"