#IntradayTradeNiftyAnalyser/backend/app/repositories/analytics/step1_repository.py
from sqlalchemy.orm import Session
from sqlalchemy import text


class PerformanceRepository:
    """
    ====================================================
    STEP 3 PERFORMANCE REPOSITORY

    Purpose:
        Read-only access to STEP 3 execution data
        and ML performance outputs.

    Sources:
        intradaytrading.step3_execution_control
        intradaytrading.step3_stock_selection
        ml.ml_stock_insights

    UI Section:
        STEP 3 PERFORMANCE

    Responsibilities:
        - Execute queries
        - Return rows

    Must NOT:
        - Calculate conversion rates
        - Calculate failure rates
        - Calculate missed opportunity rates
        - Generate suggestions
        - Generate learning

    Analytical Engine remains the source of truth.
    ====================================================
    """

    def __init__(self, db: Session):
        self.db = db

    def get_execution_control(self, trade_date: str):
        """
        ====================================================
        STEP 3 EXECUTION CONTROL

        UI Usage:
            STEP 3 PERFORMANCE

        Source:
            intradaytrading.step3_execution_control

        Purpose:
            Returns execution permissions decided
            before stock selection begins.

        Examples:
            market_context
            trade_permission
            allowed_strategies
            max_trades_allowed
            execution_allowed
        ====================================================
        """

        query = text("""
            SELECT
                trade_date,
                market_context,
                trade_permission,
                allowed_strategies,
                max_trades_allowed,
                execution_allowed,
                decided_at,
                created_at
            FROM intradaytrading.step3_execution_control
            WHERE trade_date = :trade_date
        """)

        result = self.db.execute(
            query,
            {"trade_date": trade_date}
        )

        return result.mappings().first()

    def get_stock_selection(self, trade_date: str):
        """
        ====================================================
        STEP 3 STOCK SELECTION

        UI Usage:
            STEP 3 PERFORMANCE
            TOP MISSED OPPORTUNITIES

        Source:
            intradaytrading.step3_stock_selection

        Purpose:
            Returns all stocks evaluated by STEP 3.

        Examples:
            symbol
            direction
            strategy_used
            rs_value
            tradable
            rejection_tag
            structure_valid
        ====================================================
        """

        query = text("""
            SELECT
                trade_date,
                symbol,
                direction,
                strategy_used,
                rs_value,
                gap_high,
                gap_low,
                intraday_high,
                intraday_low,
                last_higher_low,
                yesterday_close,
                vwap_value,
                structure_valid,
                tradable,
                rejection_tag,
                reason,
                evaluated_at,
                created_at
            FROM intradaytrading.step3_stock_selection
            WHERE trade_date = :trade_date
            ORDER BY symbol
        """)

        result = self.db.execute(
            query,
            {"trade_date": trade_date}
        )

        return result.mappings().all()

    def get_stock_insights(self, trade_date: str):
        """
        ====================================================
        ML PERFORMANCE OUTPUT

        UI Usage:
            STEP 3 PERFORMANCE

        Source:
            ml.ml_stock_insights

        Purpose:
            Returns precomputed performance metrics
            generated by the Analytical Engine.

        Examples:
            candidate_count
            selected_count
            total_success
            total_failure
            total_missed_opportunities
            conversion_rate
        ====================================================
        """

        query = text("""
            SELECT
                trade_date,
                candidate_count,
                selected_count,
                total_success,
                total_failure,
                total_missed_opportunities,
                conversion_rate,
                failure_rate,
                missed_opportunity_rate,
                analysis_status,
                rule_config_version,
                created_at
            FROM ml.ml_stock_insights
            WHERE trade_date = :trade_date
        """)

        result = self.db.execute(
            query,
            {"trade_date": trade_date}
        )

        return result.mappings().first()