#IntradayTradeNiftyAnalyser/backend/app/repositories/analytics/step1_repository.py  

#STEP 1 Validation
#Raw Inputs
#System Decision
#Market Reality
#Learning

from sqlalchemy.orm import Session
from sqlalchemy import text


class Step1Repository:
    """
    Repository responsible for STEP 1 validation data.

    READ ONLY.

    Sources:
        intradaytrading.step1_market_context
        ml.ml_nifty_insights
    """

    def __init__(self, db: Session):
        self.db = db

    def get_step1_context(self, trade_date: str):
        """
        Returns STEP 1 market context
        generated before market open.
        """

        query = text("""
            SELECT
                trade_date,
                preopen_price,
                gap_pct,
                gap_class,
                prior_range_size,
                prior_day_overlap,
                prior_structure_state,
                final_market_context,
                final_reason,
                created_at
            FROM intradaytrading.step1_market_context
            WHERE trade_date = :trade_date
        """)

        result = self.db.execute(
            query,
            {"trade_date": trade_date}
        )

        return result.mappings().first()

    def get_nifty_validation(self, trade_date: str):
        """
        Returns post-market NIFTY validation
        generated by the Analytical Engine.
        """

        query = text("""
            SELECT
                trade_date,
                day_type,
                trend_strength,
                total_range,
                net_move,
                pullback_depth,
                vwap_cross_count,
                vwap_hold_percentage,
                analysis_status,
                rule_config_version,
                created_at
            FROM ml.ml_nifty_insights
            WHERE trade_date = :trade_date
        """)

        result = self.db.execute(
            query,
            {"trade_date": trade_date}
        )

        return result.mappings().first()