from sqlalchemy import Column, Date, Boolean, DateTime
from sqlalchemy.sql import func
from backend.app.db.base import Base


class Step3ExecutionControl(Base):
    """
    STEP-3: Execution Control
    -------------------------
    Stores whether execution was enabled for the day
    based on STEP-1 and STEP-2.

    One row per trading day.
    Generated by the system (no user input).
    """

    __tablename__ = "step3_execution_control"

    # =========================
    # Identity
    # =========================
    trade_date = Column(Date, primary_key=True, index=True)

    # =========================
    # Decision
    # =========================
    execution_enabled = Column(Boolean, nullable=False)

    # =========================
    # Generation & lock metadata
    # =========================
    generated_at = Column(
        DateTime,
        server_default=func.now(),
        nullable=False
    )

    frozen_at = Column(DateTime, nullable=True)

    # =========================
    # Audit fields
    # =========================
    created_at = Column(
        DateTime,
        server_default=func.now(),
        nullable=False
    )

    updated_at = Column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False
    )

    # =========================
    # Debug / logging helper
    # =========================
    def __repr__(self) -> str:
        return (
            f"<Step3ExecutionControl("
            f"trade_date={self.trade_date}, "
            f"execution_enabled={self.execution_enabled}, "
            f"generated_at={self.generated_at}, "
            f"frozen_at={self.frozen_at}"
            f")>"
        )
